### ISSUE TITLE
vip-cli tools not compiling on mac

### ISSUE THREAD

**Issue by willstavescontra** [Automattic/vip#1238]
## For Automatticians!

:wave: Just a quick reminder that this is a public repo. Please don't include any internal links or sensitive data (like PII, private code, client names, site URLs, etc. If you're not sure if something is safe to share, please just ask!

If you're not an Automattician, welcome! We look forward to your contribution! :heart:

Please remove this section before submitting the issue.

---

## Expected/Desired Behavior

Fill with either one:

1. should install functioning latest version of vip-cli

## Actual Behavior

2. Build fails. Something about "`make` failed with exit code: 2" log file attached
[2023-01-13T15_18_23_514Z-debug-0.log](https://github.com/Automattic/vip-cli/files/10414390/2023-01-13T15_18_23_514Z-debug-0.log)

## Steps to Reproduce the Problem

1. run 'npm install -g @automattic/vip' based on documentation at https://docs.wpvip.com/technical-references/vip-cli/installing-vip-cli/

**Comment by sjinks** [comment]
Could you please try `@automattic/cli@2.25.1`?

**Comment by willstavescontra** [comment]
`npm install -g @automattic/cli@2.25.1 ` did not work.

However `npm install -g @automattic/vip@2.25.1` worked great. Thank You!
