### ISSUE TITLE
Add vip dev-env stop --all command.

### ISSUE THREAD

**Issue by BrookeDot** [Automattic/vip#1850]
## Desired Behavior

When running more than one `vip dev-env` each one must be stopped manually. The desired behavior is to add a command to stop all running environments such as `vip dev-env stop --all`, `vip dev-env purge`, or `vip dev-env stop` to ask if all running environments should be stopped. 

## Actual Behavior

The stop command requires a `--slug` be added otherwise an error is shown:

``` 
$ vip dev-env stop
Error: More than one environment found: example, example-2, example-3. Please re-run command with the --slug parameter for the targeted environment. 
```
## Steps to Reproduce the Problem

1. Start multiple `dev-env` with `vip dev-env start --slug`
1. Run `vip dev-env stop`

**Comment by sjinks** [comment]
See #1854
