### ISSUE TITLE
Replace Inquirer.js with Enquirer

### ISSUE THREAD

**Issue by joshbetz** [Automattic/vip#28]
Inquirer uses lodash, which is huge. We can accomplish everything we're using it for with:

* https://github.com/enquirer/prompt-password
* https://github.com/enquirer/prompt-confirm
* https://github.com/enquirer/prompt-list

This will reduce the size of our dependencies by about half. There's just one issue that needs to be resolved before we can switch https://github.com/enquirer/prompt-password/issues/2

**Comment by jonschlinkert** [comment]
FWIW we just released [Enquirer v2.0](https://github.com/enquirer/enquirer/) recently. It was a completely refactor, all of the prompts @joshbetz mentioned are now built-in, and it only has one dep for ansi styling.

**Comment by elazzabi** [comment]
Fixed by https://github.com/Automattic/vip/pull/229
