### ISSUE TITLE
Uninstalling VIP tool does not remove config

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip#69]
I uninstalled the vip tool with `npm uninstall -g @automattic/vip`, then reinstalled with `npm install -g @automattic/vip` and was still logged in.

I think the tool should remove all config, tokens, etc, when uninstalled, leaving a clean slate.

**Comment by joshbetz** [comment]
The problem, as we’ve found with the vip-cli, is that the uninstall script runs for upgrades as well. This means we’re going to log people out when new versions are released.

**Comment by simonwheatley** [comment]
Well that's awkward of NPM.

Do we think there is a security issue with what gets left behind (e.g. security tokens)? How do other products solve this issue?

**Comment by joshbetz** [comment]
No more of a security issue than there is while the CLI is installed. In most cases, any sensitive tokens would be stored in a secure keychain of some kind.

**Comment by simonwheatley** [comment]
Thanks for walking me through it.
